# Generated by Django 2.2 on 2021-02-04 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('author', models.CharField(max_length=250, null=True)),
                ('photo_book', models.ImageField(blank=True, null=True, upload_to='photos')),
                ('photo_author', models.ImageField(blank=True, null=True, upload_to='photos')),
                ('pages_no', models.IntegerField(null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('retal_price_day', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('retal_period', models.IntegerField(null=True)),
                ('active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('rented', 'rented'), ('sold', 'sold'), ('available', 'available')], max_length=50, null=True)),
                ('Category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='lms_app.Category')),
            ],
        ),
    ]
