# Generated by Django 2.2 on 2021-02-04 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('available', 'available'), ('rented', 'rented'), ('sold', 'sold')], max_length=50, null=True),
        ),
    ]
