# Generated by Django 2.2 on 2021-02-04 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0002_auto_20210204_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='retal_period',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('sold', 'sold'), ('available', 'available'), ('rented', 'rented')], max_length=50, null=True),
        ),
    ]
