# Generated by Django 2.2 on 2021-02-05 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0003_auto_20210204_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('sold', 'sold'), ('rented', 'rented'), ('available', 'available')], max_length=50, null=True),
        ),
    ]
