# Generated by Django 2.2 on 2021-02-05 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0004_auto_20210205_1903'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='Category',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('rented', 'rented'), ('sold', 'sold'), ('available', 'available')], max_length=50, null=True),
        ),
    ]
