# Generated by Django 2.2 on 2021-02-06 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0006_auto_20210205_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('sold', 'sold'), ('available', 'available'), ('rented', 'rented')], max_length=50, null=True),
        ),
    ]
